name: voo_logger_devtools
description: DevTools extension for Voo Logger
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.4.0
  flutter_web_plugins:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7

dev_dependencies:
  build_web_compilers: ^4.2.0
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
