name: voo_logger_devtools
description: DevTools extension for Voo Logger
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.3.0-dev.0
  flutter_web_plugins:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

dev_dependencies:
  build_web_compilers: ^4.0.7
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
