// Mocks generated by Mockito 5.4.6 from annotations
// in voo_logging/test/features/devtools_extension/presentation/pages/voo_logger_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:voo_logging/features/devtools_extension/domain/repositories/devtools_log_repository.dart' as _i2;
import 'package:voo_logging/features/devtools_extension/presentation/blocs/log_bloc.dart' as _i4;
import 'package:voo_logging/features/devtools_extension/presentation/blocs/log_event.dart' as _i7;
import 'package:voo_logging/features/devtools_extension/presentation/blocs/log_state.dart' as _i3;
import 'package:voo_logging/features/logging/data/models/log_entry_model.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDevToolsLogRepository_0 extends _i1.SmartFake implements _i2.DevToolsLogRepository {
  _FakeDevToolsLogRepository_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeLogState_1 extends _i1.SmartFake implements _i3.LogState {
  _FakeLogState_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [LogBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogBloc extends _i1.Mock implements _i4.LogBloc {
  MockLogBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DevToolsLogRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository), returnValue: _FakeDevToolsLogRepository_0(this, Invocation.getter(#repository)))
          as _i2.DevToolsLogRepository);

  @override
  set logStreamSubscription(_i5.StreamSubscription<_i6.LogEntryModel>? _logStreamSubscription) =>
      super.noSuchMethod(Invocation.setter(#logStreamSubscription, _logStreamSubscription), returnValueForMissingStub: null);

  @override
  _i3.LogState get state => (super.noSuchMethod(Invocation.getter(#state), returnValue: _FakeLogState_1(this, Invocation.getter(#state))) as _i3.LogState);

  @override
  _i5.Stream<_i3.LogState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream), returnValue: _i5.Stream<_i3.LogState>.empty()) as _i5.Stream<_i3.LogState>);

  @override
  bool get isClosed => (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false) as bool);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(Invocation.method(#close, []), returnValue: _i5.Future<void>.value(), returnValueForMissingStub: _i5.Future<void>.value())
          as _i5.Future<void>);

  @override
  void add(_i7.LogEvent? event) => super.noSuchMethod(Invocation.method(#add, [event]), returnValueForMissingStub: null);

  @override
  void onEvent(_i7.LogEvent? event) => super.noSuchMethod(Invocation.method(#onEvent, [event]), returnValueForMissingStub: null);

  @override
  void emit(_i3.LogState? state) => super.noSuchMethod(Invocation.method(#emit, [state]), returnValueForMissingStub: null);

  @override
  void on<E extends _i7.LogEvent>(_i8.EventHandler<E, _i3.LogState>? handler, {_i8.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(Invocation.method(#on, [handler], {#transformer: transformer}), returnValueForMissingStub: null);

  @override
  void onTransition(_i8.Transition<_i7.LogEvent, _i3.LogState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]), returnValueForMissingStub: null);

  @override
  void onChange(_i8.Change<_i3.LogState>? change) => super.noSuchMethod(Invocation.method(#onChange, [change]), returnValueForMissingStub: null);

  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]), returnValueForMissingStub: null);

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]), returnValueForMissingStub: null);
}
