name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # matches v1.0.0, v2.1.0, etc.
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run a dry run (no actual publish)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Run analyzer
        run: flutter analyze

      - name: Check publish readiness
        run: flutter pub publish --dry-run

  publish:
    needs: analyze-and-test
    if: github.event_name == 'push' || github.event.inputs.dry_run == 'false'
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1

  create-release:
    needs: publish
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract changelog entry
        id: changelog
        run: |
          VERSION="${{ steps.extract_version.outputs.version }}"
          VERSION_NUMBER=${VERSION#v}

          # Extract the changelog entry for this version
          CHANGELOG_ENTRY=$(awk -v ver="## $VERSION_NUMBER" '
            $0 ~ ver {flag=1; next}
            /^## / && flag {exit}
            flag {print}
          ' CHANGELOG.md)

          # Write to file to preserve formatting
          echo "$CHANGELOG_ENTRY" > changelog_entry.md
          echo "changelog_file=changelog_entry.md" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ steps.extract_version.outputs.version }}
          body_path: ${{ steps.changelog.outputs.changelog_file }}
          draft: false
          prerelease: ${{ contains(steps.extract_version.outputs.version, '-') }}
