name: Publish to pub.dev

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run a dry run (no actual publish)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    # Only run on main branch, release branches, or tags
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.ref == 'refs/heads/main' ||
      startsWith(github.ref, 'refs/heads/release/') ||
      startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Run tests
        run: flutter test
        
      - name: Run analyzer
        run: flutter analyze
      
      - name: Check publish readiness
        run: flutter pub publish --dry-run
      
      - name: Setup pub credentials
        if: |
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'false')
        run: |
          mkdir -p ~/.pub-cache
          echo '${{ secrets.PUB_CREDENTIALS }}' > ~/.pub-cache/credentials.json
      
      - name: Publish to pub.dev (dry run)
        if: |
          github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'true'
        run: flutter pub publish --dry-run
        
      - name: Publish to pub.dev
        if: |
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'false')
        run: flutter pub publish --force

  publish-notification:
    needs: publish
    runs-on: ubuntu-latest
    if: |
      success() && 
      ((github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) ||
       (github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'false'))
    
    steps:
      - name: Extract version
        id: extract_version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION="manual"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          body: |
            ## Voo Logging ${{ steps.extract_version.outputs.version }}
            
            Published to [pub.dev](https://pub.dev/packages/voo_logging)
            
            ### What's Changed
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false